
utils::globalVariables(c('.', 'accepted_value', 'application', 'best_rows', 'check', 'check_denom', 'check_desc',
                       'check_description', 'check_id', 'check_name', 'check_type', 'cohort', 'cohort_1',
                       'cohort_1_denom', 'cohort_1_in_2', 'cohort_1_only', 'cohort_2', 'cohort_2_denom',
                       'cohort_2_in_1', 'cohort_2_only', 'cohort_label', 'combined', 'concept',
                       'concept_code', 'concept_id', 'concept_name', 'concept_pt_ct', 'concept_pts',
                       'concept_rows', 'concepts', 'database_version', 'date1', 'date2', 'date_diff', 'domain',
                       'fact_pts', 'fact_visits', 'include', 'lag_1', 'lag_12', 'lag_1_plus', 'measure',
                       'measurement_column', 'missing_flag', 'missing_visits_distinct',
                       'missing_visits_total', 'time_end', 'time_start', 'no_fact_pts', 'no_fact_pts_prop',
                       'no_fact_visits', 'no_fact_visits_prop', 'person_id', 'prop_total_change',
                       'prop_total_viol', 'rate_mult', 'row_ratio', 'site', 'src_value_ct',
                       'table_application', 'temp', 'this_round_pre', 'time_span', 'tot_ct',
                       'tot_dist_concept_ct', 'tot_prop', 'total_concept_ct', 'total_ct', 'total_denom_ct',
                       'total_id', 'total_pt_ct', 'total_pts', 'total_row_ct', 'total_rows',
                       'total_unmapped_row_ct', 'total_viol_concept_ct', 'total_viol_ct',
                       'total_viol_pt_ct', 'total_visits', 'unmapped_prop', 'unmapped_rows', 'value',
                       'version_current', 'version_previous', 'visit_na', 'visit_occurrence_id',
                       'visits_narrowed', 'vocabulary_id', 'year_date', 'visit_type', 'max_val',
                       'mean_val', 'median_val', 'min_val', 'q1', 'q3', 'site_anon', 'sitenum',
                       'tot_viol_ct'))
